import { Provider } from '@/types'

export const providers: Provider[] = [
  {
    id: 'openai',
    name: 'OpenAI',
    color: '#10A37F',
    icon: 'Sparkles',
    baseUrl: 'https://api.openai.com',
    docsUrl: 'https://platform.openai.com/docs',
    requiresKey: true,
    keyPlaceholder: 'sk-...',
    defaultModel: 'gpt-4o',
    modelEndpoint: '/v1/models',
    supportsStreaming: true,
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    color: '#D97757',
    icon: 'Brain',
    baseUrl: 'https://api.anthropic.com/v1',
    docsUrl: 'https://docs.anthropic.com',
    requiresKey: true,
    keyPlaceholder: 'sk-ant-...',
    defaultModel: 'claude-sonnet-4',
    modelEndpoint: '/v1/models',
    supportsStreaming: true,
  },
  {
    id: 'google',
    name: 'Google AI Studio',
    color: '#4285F4',
    icon: 'Gem',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    docsUrl: 'https://ai.google.dev',
    requiresKey: true,
    keyPlaceholder: 'AIza...',
    defaultModel: 'gemini-2.0-flash',
    modelEndpoint: '/v1/models',
    supportsStreaming: true,
  },
  {
    id: 'groq',
    name: 'Groq',
    color: '#F55036',
    icon: 'Zap',
    baseUrl: 'https://api.groq.com/openai',
    docsUrl: 'https://console.groq.com/docs',
    requiresKey: true,
    keyPlaceholder: 'gsk_...',
    defaultModel: 'llama-3.3-70b-versatile',
    modelEndpoint: '/v1/models',
    supportsStreaming: true,
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    color: '#8B5CF6',
    icon: 'Route',
    baseUrl: 'https://openrouter.ai/api',
    docsUrl: 'https://openrouter.ai/docs',
    requiresKey: true,
    keyPlaceholder: 'sk-or-...',
    defaultModel: 'meta-llama/llama-3.1-8b-instruct:free',
    modelEndpoint: '/v1/models',
    supportsStreaming: true,
  },
  {
    id: 'together',
    name: 'Together AI',
    color: '#FF6B6B',
    icon: 'Users',
    baseUrl: 'https://api.together.xyz',
    docsUrl: 'https://docs.together.ai',
    requiresKey: true,
    keyPlaceholder: '...',
    defaultModel: 'meta-llama/Llama-3-70b-chat-hf',
    modelEndpoint: '/v1/models',
    supportsStreaming: true,
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    color: '#FF7000',
    icon: 'Wind',
    baseUrl: 'https://api.mistral.ai',
    docsUrl: 'https://docs.mistral.ai',
    requiresKey: true,
    keyPlaceholder: '...',
    defaultModel: 'mistral-large-latest',
    modelEndpoint: '/v1/models',
    supportsStreaming: true,
  },
  {
    id: 'cohere',
    name: 'Cohere',
    color: '#39594D',
    icon: 'MessageSquare',
    baseUrl: 'https://api.cohere.ai/compatibility',
    docsUrl: 'https://docs.cohere.com',
    requiresKey: true,
    keyPlaceholder: '...',
    defaultModel: 'command-r-plus',
    modelEndpoint: '/v1/models',
    supportsStreaming: true,
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    color: '#1E40AF',
    icon: 'Search',
    baseUrl: 'https://api.deepseek.com',
    docsUrl: 'https://platform.deepseek.com/docs',
    requiresKey: true,
    keyPlaceholder: 'sk-...',
    defaultModel: 'deepseek-chat',
    modelEndpoint: '/v1/models',
    supportsStreaming: true,
  },
  {
    id: 'xai',
    name: 'xAI Grok',
    color: '#000000',
    icon: 'Twitter',
    baseUrl: 'https://api.x.ai',
    docsUrl: 'https://docs.x.ai',
    requiresKey: true,
    keyPlaceholder: 'xai-...',
    defaultModel: 'grok-2-latest',
    modelEndpoint: '/v1/models',
    supportsStreaming: true,
  },
  {
    id: 'perplexity',
    name: 'Perplexity AI',
    color: '#20808D',
    icon: 'Compass',
    baseUrl: 'https://api.perplexity.ai',
    docsUrl: 'https://docs.perplexity.ai',
    requiresKey: true,
    keyPlaceholder: 'pplx-...',
    defaultModel: 'sonar-pro',
    modelEndpoint: '/v1/models',
    supportsStreaming: true,
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    color: '#FF4500',
    icon: 'Flame',
    baseUrl: 'https://api.fireworks.ai/inference',
    docsUrl: 'https://docs.fireworks.ai',
    requiresKey: true,
    keyPlaceholder: 'fw_...',
    defaultModel: 'accounts/fireworks/models/llama-v3p1-70b-instruct',
    modelEndpoint: '/v1/models',
    supportsStreaming: true,
  },
  {
    id: 'ollama',
    name: 'Ollama',
    color: '#000000',
    icon: 'Server',
    baseUrl: 'http://localhost:11434/v1',
    docsUrl: 'https://ollama.ai/docs',
    requiresKey: false,
    keyPlaceholder: '',
    defaultModel: 'llama3.2',
    modelEndpoint: '/v1/models',
    supportsStreaming: true,
    autoDetect: true,
  },
  {
    id: 'lmstudio',
    name: 'LM Studio',
    color: '#5B21B6',
    icon: 'Monitor',
    baseUrl: 'http://localhost:1234/v1',
    docsUrl: 'https://lmstudio.ai/docs',
    requiresKey: false,
    keyPlaceholder: '',
    defaultModel: 'auto-detect',
    modelEndpoint: '/v1/models',
    supportsStreaming: true,
    autoDetect: true,
  },
  {
    id: 'custom',
    name: 'Custom Provider',
    color: '#6B7280',
    icon: 'Settings',
    baseUrl: '',
    docsUrl: '',
    requiresKey: true,
    keyPlaceholder: 'optional',
    defaultModel: '',
    modelEndpoint: '/v1/models',
    supportsStreaming: true,
  },
]
